package agent

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func parseJSONC(t *testing.T, body []byte) map[string]any {
	t.Helper()
	var lines []string
	for _, l := range strings.Split(string(body), "\n") {
		if !strings.HasPrefix(strings.TrimSpace(l), "//") {
			lines = append(lines, l)
		}
	}
	var out map[string]any
	if err := json.Unmarshal([]byte(strings.Join(lines, "\n")), &out); err != nil {
		t.Fatalf("not JSON after stripping comments: %v\n%s", err, body)
	}
	return out
}

func TestOpencodeInstanceConfig(t *testing.T) {
	d := withDefaults(Definition{Name: "x-poster", Description: "Posts X threads.",
		Permissions: Permissions{Bash: "ask", BashAllow: []string{"git log *"}}})
	body, err := OpencodeInstanceConfig(d, "/base/x-poster", map[string]mcpEntry{
		"x": {Command: "x-mcp", Args: []string{"--live"}, Env: map[string]string{"X_TOKEN": "${X_TOKEN}"}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(body), "// Generated by ccmux") {
		t.Error("header missing")
	}
	cfg := parseJSONC(t, body)
	if ins := cfg["instructions"].([]any); len(ins) != 1 || ins[0] != "/base/x-poster/AGENTS.md" {
		t.Errorf("instructions %v", ins)
	}
	if cfg["snapshot"] != false {
		t.Error("snapshot must be false")
	}
	mcp := cfg["mcp"].(map[string]any)
	if _, ok := mcp["claude-peers"]; !ok {
		t.Error("peers bus server missing")
	}
	x := mcp["x"].(map[string]any)
	if cmd := x["command"].([]any); len(cmd) != 2 || cmd[0] != "x-mcp" || cmd[1] != "--live" {
		t.Errorf("mcp command %v", cmd)
	}
	if x["environment"].(map[string]any)["X_TOKEN"] != "${X_TOKEN}" {
		t.Error("mcp env not carried")
	}
	ag := cfg["agent"].(map[string]any)["x-poster"].(map[string]any)
	perm := ag["permission"].(map[string]any)
	if perm["read"] != "allow" || perm["edit"] != "allow" || perm["webfetch"] != "ask" {
		t.Errorf("gates %v", perm)
	}
	bash := perm["bash"].(map[string]any)
	if bash["*"] != "ask" || bash["git log *"] != "allow" {
		t.Errorf("bash map %v", bash)
	}
}

func TestWriteInstanceConfigRegeneratesFromBase(t *testing.T) {
	s := testStore(t)
	d, err := s.Save(Definition{Name: "kb-writer", Description: "Writes KB articles.", Instructions: "r\n"})
	if err != nil {
		t.Fatal(err)
	}
	os.WriteFile(filepath.Join(s.Dir("kb-writer"), "mcp.json"), []byte(`{"kb":{"command":"kb-mcp"}}`), 0o644)
	inst := t.TempDir()
	if err := s.WriteInstanceConfig(d, inst); err != nil {
		t.Fatal(err)
	}
	body, _ := os.ReadFile(filepath.Join(inst, InstanceConfigFile))
	cfg := parseJSONC(t, body)
	if _, ok := cfg["mcp"].(map[string]any)["kb"]; !ok {
		t.Error("base mcp.json server not included")
	}
	os.WriteFile(filepath.Join(s.Dir("kb-writer"), "mcp.json"), []byte(`{bad`), 0o644)
	if err := s.WriteInstanceConfig(d, inst); err == nil {
		t.Error("malformed base mcp.json must fail loudly")
	}
}
