package agent

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// InstanceConfigFile is the daemon-owned file inside an instance folder.
// Unlike everything else there it is REGENERATED at every start, so a base
// change reaches the instance on its next run; the header says so.
const InstanceConfigFile = "opencode.jsonc"

const instanceConfigHeader = "// Generated by ccmux from the base agent at every start. Do not edit;\n" +
	"// project instructions go in AGENTS.md, project skills in .claude/skills/.\n"

// mcpEntry is the harness-neutral MCP shape of a base mcp.json.
type mcpEntry struct {
	Command string            `json:"command"`
	Args    []string          `json:"args,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
}

// OpencodeInstanceConfig renders the opencode project config for one
// instance of base d whose folder is baseDir. It carries what the pane-level
// OPENCODE_CONFIG_CONTENT (manager/opencode.go) does not: the base
// instructions, the agent's permissions as an opencode primary agent, the
// base's MCP servers plus the peers bus, and snapshots off once more in case
// a project config turned them on.
func OpencodeInstanceConfig(d Definition, baseDir string, mcp map[string]mcpEntry, plugins []string, defaultModel string) ([]byte, error) {
	servers := map[string]any{
		"claude-peers": map[string]any{"type": "local", "command": []string{"ccmux-peers"}, "enabled": true},
	}
	for name, e := range mcp {
		entry := map[string]any{"type": "local", "command": append([]string{e.Command}, e.Args...), "enabled": true}
		if len(e.Env) > 0 {
			entry["environment"] = e.Env
		}
		servers[name] = entry
	}
	cfg := map[string]any{
		"$schema":      "https://opencode.ai/config.json",
		"instructions": []string{filepath.Join(baseDir, fileAgents)},
		"snapshot":     false,
		"mcp":          servers,
		"plugin":       plugins,
		"agent": map[string]any{
			d.Name: map[string]any{
				"mode":        "primary",
				"description": d.Description,
				"permission":  opencodePermission(d.Permissions),
			},
		},
	}
	// Without a model opencode falls back to whatever provider the user last
	// logged into (a ChatGPT login, seen live 2026-09-05), bypassing the
	// pane's routed account entirely. The base's pin wins; else the daemon
	// default, which names the anthropic provider so traffic rides the proxy.
	if model := firstNonEmpty(d.Model, defaultModel); model != "" {
		cfg["model"] = model
		cfg["agent"].(map[string]any)[d.Name].(map[string]any)["model"] = model
	}
	body, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return nil, err
	}
	return append([]byte(instanceConfigHeader), append(body, '\n')...), nil
}

// opencodePermission maps the neutral vocabulary onto opencode's permission
// block: the four gates directly, bash as a pattern map whose "*" carries
// the gate and each BashAllow pattern is "allow".
func opencodePermission(p Permissions) map[string]any {
	bash := map[string]string{"*": p.Bash}
	for _, pat := range p.BashAllow {
		bash[pat] = "allow"
	}
	return map[string]any{
		"read":     p.Read,
		"edit":     p.Edit,
		"webfetch": p.Webfetch,
		"bash":     bash,
	}
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}

// ReadMCP loads a base's mcp.json in the neutral shape; a missing file is an
// empty set, a malformed one is an error the start must surface.
func ReadMCP(baseDir string) (map[string]mcpEntry, error) {
	raw, err := os.ReadFile(filepath.Join(baseDir, fileMCP))
	if errors.Is(err, os.ErrNotExist) {
		return map[string]mcpEntry{}, nil
	}
	if err != nil {
		return nil, err
	}
	out := map[string]mcpEntry{}
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// DefaultModel is what an instance runs on when its base pins none — in
// opencode's provider/model form, on the anthropic provider so the request
// goes through the pane proxy to the routed account. Set from -agents-model.
var DefaultModel = "anthropic/claude-sonnet-5"

// WriteInstanceConfig regenerates the instance's opencode.jsonc from base d.
func (s *Store) WriteInstanceConfig(d Definition, instanceDir string) error {
	if !ValidName(d.Name) {
		return fmt.Errorf("agent name %q invalid", d.Name)
	}
	mcp, err := ReadMCP(s.Dir(d.Name))
	if err != nil {
		return err
	}
	plugin, err := s.EnsurePlugin()
	if err != nil {
		return err
	}
	body, err := OpencodeInstanceConfig(d, s.Dir(d.Name), mcp, []string{plugin}, DefaultModel)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(instanceDir, InstanceConfigFile), body, 0o644)
}
