package portdetect

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	yaml "go.yaml.in/yaml/v3"
)

// ComposeFiles returns the compose file set `docker compose` would load from
// dir with no -f flags: the first existing canonical file, plus its .override
// companion when present. Nil when the repo has no canonical compose file.
// Setting COMPOSE_FILE disables compose's own default lookup, so anything the
// daemon exports there must reproduce this list exactly — a forgotten
// override file would silently change what `up` starts.
func ComposeFiles(dir string) []string {
	for _, base := range []string{"compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml"} {
		main := filepath.Join(dir, base)
		if _, err := os.Stat(main); err != nil {
			continue
		}
		files := []string{main}
		stem := strings.TrimSuffix(base, filepath.Ext(base))
		for _, ext := range []string{".yaml", ".yml"} {
			if ov := filepath.Join(dir, stem+".override"+ext); fileExists(ov) {
				files = append(files, ov)
				break
			}
		}
		return files
	}
	return nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// ComposeOverride builds the content of an extra compose file that moves
// published host ports onto the daemon-allocated hostname ports: remap is
// {detected host port → allocated port}. Returns the file set COMPOSE_FILE
// must list (canonical files, the caller appends the override's own path) and
// the override YAML. ok is false when the repo has no compose files or no
// published port matches remap — no override should be written then.
//
// The generated ports lists carry the `!override` tag (compose v2.24.4+):
// compose merges ports lists by APPENDING, which would publish both the old
// conflicting port and the new one.
func ComposeOverride(dir string, remap map[int]int) (files []string, content string, ok bool) {
	files = ComposeFiles(dir)
	if len(files) == 0 || len(remap) == 0 {
		return nil, "", false
	}

	// Per-service final ports list, accumulated across the file set in load
	// order (compose appends on merge, so concatenation reproduces the list).
	entries := map[string][]string{}
	changed := map[string]bool{}
	for _, file := range files {
		raw, err := os.ReadFile(file)
		if err != nil {
			continue
		}
		var doc composeDoc
		if yaml.Unmarshal(raw, &doc) != nil {
			continue
		}
		for name, svc := range doc.Services {
			for _, node := range svc.Ports {
				entry, didChange := rewritePortEntry(node, remap)
				if entry == "" {
					continue
				}
				entries[name] = append(entries[name], entry)
				changed[name] = changed[name] || didChange
			}
		}
	}
	if len(changed) == 0 {
		return nil, "", false
	}

	names := make([]string, 0, len(changed))
	for name := range changed {
		if changed[name] {
			names = append(names, name)
		}
	}
	if len(names) == 0 {
		return nil, "", false
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# Generated by ccmuxd — do not edit. Rewritten whenever the workspace's\n")
	b.WriteString("# hostnames change: moves published dev ports onto the allocated hostname\n")
	b.WriteString("# ports so the mapped https names route to what actually runs.\n")
	b.WriteString("services:\n")
	for _, name := range names {
		fmt.Fprintf(&b, "  %s:\n    ports: !override\n", name)
		for _, e := range entries[name] {
			fmt.Fprintf(&b, "      - %q\n", e)
		}
	}
	return files, b.String(), true
}

// rewritePortEntry renders one ports-list node as a short-syntax string,
// swapping the host side per remap. Unparseable or portless entries come back
// unchanged so the !override list stays complete; "" drops the node entirely
// (only for nodes yaml itself cannot render).
func rewritePortEntry(node yaml.Node, remap map[int]int) (entry string, changed bool) {
	switch node.Kind {
	case yaml.ScalarNode:
		raw := envDefault.ReplaceAllString(node.Value, "$1")
		host := hostPortOf(node.Value)
		to, hit := remap[host]
		if host == 0 || !hit || to == host {
			return raw, false
		}
		parts := strings.Split(strings.TrimSuffix(raw, "/tcp"), ":")
		switch len(parts) {
		case 2:
			return strconv.Itoa(to) + ":" + parts[1], true
		case 3:
			return parts[0] + ":" + strconv.Itoa(to) + ":" + parts[2], true
		}
		return raw, false
	case yaml.MappingNode:
		var long struct {
			Published string `yaml:"published"`
			Target    int    `yaml:"target"`
		}
		if node.Decode(&long) != nil || long.Target == 0 {
			return "", false
		}
		host, _ := strconv.Atoi(long.Published)
		if to, hit := remap[host]; hit && host != 0 && to != host {
			return strconv.Itoa(to) + ":" + strconv.Itoa(long.Target), true
		}
		if long.Published == "" {
			return strconv.Itoa(long.Target), false
		}
		return long.Published + ":" + strconv.Itoa(long.Target), false
	}
	return "", false
}
