package portdetect

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	yaml "go.yaml.in/yaml/v3"
)

// ComposeFiles returns the compose file set `docker compose` would load from
// dir with no -f flags: the first existing canonical file, plus its .override
// companion when present. Nil when the repo has no canonical compose file.
// Setting COMPOSE_FILE disables compose's own default lookup, so anything the
// daemon exports there must reproduce this list exactly — a forgotten
// override file would silently change what `up` starts.
func ComposeFiles(dir string) []string {
	for _, base := range []string{"compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml"} {
		main := filepath.Join(dir, base)
		if !fileExists(main) {
			continue
		}
		files := []string{main}
		stem := strings.TrimSuffix(base, filepath.Ext(base))
		for _, ext := range []string{".yaml", ".yml"} {
			if ov := filepath.Join(dir, stem+".override"+ext); fileExists(ov) {
				files = append(files, ov)
				break
			}
		}
		return files
	}
	return nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// ComposeOverride builds the content of an extra compose file that moves
// published host ports onto the daemon-allocated hostname ports: remap is
// {detected host port → allocated port}. Returns the file set COMPOSE_FILE
// must list (canonical files, the caller appends the override's own path) and
// the override YAML. Empty files with a nil error means no override applies
// (no compose files, or no published port matches remap).
//
// A file in the set that cannot be read or parsed is an ERROR, never a skip:
// the generated `!override` tag replaces a service's WHOLE ports list
// (compose v2.24.4+; plain merge APPENDS, which would publish both the old
// conflicting port and the new one), so building the list from a partial
// file set would silently unpublish the failed file's ports. No override at
// all beats a wrong one. Untouched entries ride along verbatim, as original
// yaml nodes, so env interpolation, protocol, host_ip and mode all survive.
func ComposeOverride(dir string, remap map[int]int) (files []string, content string, err error) {
	files = ComposeFiles(dir)
	if len(files) == 0 || len(remap) == 0 {
		return nil, "", nil
	}

	// Per-service final ports list, accumulated across the file set in load
	// order (compose appends on merge, so concatenation reproduces the list).
	entries := map[string][]*yaml.Node{}
	changed := map[string]bool{}
	for _, file := range files {
		raw, err := os.ReadFile(file)
		if err != nil {
			return nil, "", fmt.Errorf("compose override: read %s: %w", file, err)
		}
		var doc composeDoc
		if err := yaml.Unmarshal(raw, &doc); err != nil {
			return nil, "", fmt.Errorf("compose override: parse %s: %w", file, err)
		}
		for name, svc := range doc.Services {
			for i := range svc.Ports {
				node := svc.Ports[i]
				out, didChange := remapPortNode(&node, remap)
				entries[name] = append(entries[name], out)
				changed[name] = changed[name] || didChange
			}
		}
	}

	names := make([]string, 0, len(changed))
	for name, did := range changed {
		if did {
			names = append(names, name)
		}
	}
	if len(names) == 0 {
		return nil, "", nil
	}
	sort.Strings(names)

	content, err = renderOverride(names, entries)
	if err != nil {
		return nil, "", err
	}
	return files, content, nil
}

// renderOverride marshals {services: {name: {ports: !override [...]}}} for
// the named services. Built as yaml nodes so the untouched port entries are
// the ORIGINAL parsed nodes, emitted back byte-for-byte in meaning.
func renderOverride(names []string, entries map[string][]*yaml.Node) (string, error) {
	scalar := func(v string) *yaml.Node {
		return &yaml.Node{Kind: yaml.ScalarNode, Value: v}
	}
	services := &yaml.Node{Kind: yaml.MappingNode}
	for _, name := range names {
		ports := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!override", Content: entries[name]}
		svc := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{scalar("ports"), ports}}
		services.Content = append(services.Content, scalar(name), svc)
	}
	doc := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{scalar("services"), services}}
	b, err := yaml.Marshal(doc)
	if err != nil {
		return "", fmt.Errorf("compose override: render: %w", err)
	}
	return "# Generated by ccmuxd — do not edit. Rewritten whenever the workspace's\n" +
		"# hostnames change: moves published dev ports onto the allocated hostname\n" +
		"# ports so the mapped https names route to what actually runs.\n" +
		string(b), nil
}

// remapPortNode routes one ports-list entry to the parser for its yaml shape.
// Both return the UNTOUCHED original node when the entry's host port isn't
// being remapped, or a fresh node with only the host side swapped.
func remapPortNode(node *yaml.Node, remap map[int]int) (out *yaml.Node, changed bool) {
	switch node.Kind {
	case yaml.ScalarNode:
		return remapShortPort(node, remap)
	case yaml.MappingNode:
		return remapLongPort(node, remap)
	}
	return node, false
}

// remapTarget answers whether host is a port this remap actually moves.
func remapTarget(host int, remap map[int]int) (int, bool) {
	to, hit := remap[host]
	return to, hit && host != 0 && to != host
}

// remapShortPort rewrites a short-syntax entry ("3000:3000",
// "127.0.0.1:5900:5900"). The rewritten entry is built from the interpolated
// form — its host side is being replaced anyway, and ${VAR:-default} on the
// container side of a remapped dev port has no meaning left to preserve.
func remapShortPort(node *yaml.Node, remap map[int]int) (*yaml.Node, bool) {
	to, hit := remapTarget(hostPortOf(node.Value), remap)
	if !hit {
		return node, false
	}
	interp := envDefault.ReplaceAllString(node.Value, "$1")
	parts := strings.Split(strings.TrimSuffix(interp, "/tcp"), ":")
	var v string
	switch len(parts) {
	case 2:
		v = strconv.Itoa(to) + ":" + parts[1]
	case 3:
		v = parts[0] + ":" + strconv.Itoa(to) + ":" + parts[2]
	default:
		return node, false
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Style: yaml.DoubleQuotedStyle, Value: v}, true
}

// remapLongPort rewrites a long-syntax {published, target, ...} mapping by
// re-encoding the full mapping with only published swapped, keeping
// target/protocol/mode/host_ip and anything else it carries. udp entries are
// never dev servers and pass through verbatim.
func remapLongPort(node *yaml.Node, remap map[int]int) (*yaml.Node, bool) {
	var long struct {
		Published string `yaml:"published"`
		Protocol  string `yaml:"protocol"`
	}
	if node.Decode(&long) != nil || long.Protocol == "udp" {
		return node, false
	}
	host, _ := strconv.Atoi(long.Published)
	to, hit := remapTarget(host, remap)
	if !hit {
		return node, false
	}
	var full map[string]any
	if node.Decode(&full) != nil {
		return node, false
	}
	full["published"] = strconv.Itoa(to)
	fresh := &yaml.Node{}
	if fresh.Encode(full) != nil {
		return node, false
	}
	return fresh, true
}
