package portdetect

import (
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	yaml "go.yaml.in/yaml/v3"
)

// ComposeFiles returns the compose file set `docker compose` would load from
// dir with no -f flags: the first existing canonical file, plus its .override
// companion when present. Nil when the repo has no canonical compose file.
// Setting COMPOSE_FILE disables compose's own default lookup, so anything the
// daemon exports there must reproduce this list exactly — a forgotten
// override file would silently change what `up` starts.
func ComposeFiles(dir string) []string {
	for _, base := range []string{"compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml"} {
		main := filepath.Join(dir, base)
		if _, err := os.Stat(main); err != nil {
			continue
		}
		files := []string{main}
		stem := strings.TrimSuffix(base, filepath.Ext(base))
		for _, ext := range []string{".yaml", ".yml"} {
			if ov := filepath.Join(dir, stem+".override"+ext); fileExists(ov) {
				files = append(files, ov)
				break
			}
		}
		return files
	}
	return nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// ComposeOverride builds the content of an extra compose file that moves
// published host ports onto the daemon-allocated hostname ports: remap is
// {detected host port → allocated port}. Returns the file set COMPOSE_FILE
// must list (canonical files, the caller appends the override's own path) and
// the override YAML. ok is false when the repo has no compose files or no
// published port matches remap — no override should be written then.
//
// The generated ports lists carry the `!override` tag (compose v2.24.4+):
// compose merges ports lists by APPENDING, which would publish both the old
// conflicting port and the new one. Because !override replaces the service's
// WHOLE list, untouched entries ride along — verbatim, as original yaml
// nodes, so env interpolation, protocol, host_ip and mode all survive.
func ComposeOverride(dir string, remap map[int]int) (files []string, content string, ok bool) {
	files = ComposeFiles(dir)
	if len(files) == 0 || len(remap) == 0 {
		return nil, "", false
	}

	// Per-service final ports list, accumulated across the file set in load
	// order (compose appends on merge, so concatenation reproduces the list).
	entries := map[string][]*yaml.Node{}
	changed := map[string]bool{}
	for _, file := range files {
		raw, err := os.ReadFile(file)
		if err != nil {
			continue
		}
		var doc composeDoc
		if yaml.Unmarshal(raw, &doc) != nil {
			continue
		}
		for name, svc := range doc.Services {
			for i := range svc.Ports {
				node := svc.Ports[i]
				out, didChange := remapPortNode(&node, remap)
				entries[name] = append(entries[name], out)
				changed[name] = changed[name] || didChange
			}
		}
	}

	names := make([]string, 0, len(changed))
	for name, did := range changed {
		if did {
			names = append(names, name)
		}
	}
	if len(names) == 0 {
		return nil, "", false
	}
	sort.Strings(names)

	content, ok = renderOverride(names, entries)
	if !ok {
		return nil, "", false
	}
	return files, content, true
}

// renderOverride marshals {services: {name: {ports: !override [...]}}} for
// the named services. Built as yaml nodes so the untouched port entries are
// the ORIGINAL parsed nodes, emitted back byte-for-byte in meaning.
func renderOverride(names []string, entries map[string][]*yaml.Node) (string, bool) {
	scalar := func(v string) *yaml.Node {
		return &yaml.Node{Kind: yaml.ScalarNode, Value: v}
	}
	services := &yaml.Node{Kind: yaml.MappingNode}
	for _, name := range names {
		ports := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!override", Content: entries[name]}
		svc := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{scalar("ports"), ports}}
		services.Content = append(services.Content, scalar(name), svc)
	}
	doc := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{scalar("services"), services}}
	b, err := yaml.Marshal(doc)
	if err != nil {
		return "", false
	}
	return "# Generated by ccmuxd — do not edit. Rewritten whenever the workspace's\n" +
		"# hostnames change: moves published dev ports onto the allocated hostname\n" +
		"# ports so the mapped https names route to what actually runs.\n" +
		string(b), true
}

// remapPortNode returns the node to emit for one ports-list entry: the
// UNTOUCHED original node when its host port isn't being remapped (so
// interpolation like ${WEB_PORT:-3000}, /udp suffixes and long-syntax extras
// survive verbatim), or a fresh node with only the host side swapped.
func remapPortNode(node *yaml.Node, remap map[int]int) (out *yaml.Node, changed bool) {
	switch node.Kind {
	case yaml.ScalarNode:
		host := hostPortOf(node.Value)
		to, hit := remap[host]
		if host == 0 || !hit || to == host {
			return node, false
		}
		// The rewritten entry is built from the interpolated form — its host
		// side is being replaced anyway, and ${VAR:-default} on the container
		// side of a remapped dev port has no meaning left to preserve.
		interp := envDefault.ReplaceAllString(node.Value, "$1")
		parts := strings.Split(strings.TrimSuffix(interp, "/tcp"), ":")
		var v string
		switch len(parts) {
		case 2:
			v = strconv.Itoa(to) + ":" + parts[1]
		case 3:
			v = parts[0] + ":" + strconv.Itoa(to) + ":" + parts[2]
		default:
			return node, false
		}
		return &yaml.Node{Kind: yaml.ScalarNode, Style: yaml.DoubleQuotedStyle, Value: v}, true
	case yaml.MappingNode:
		var long struct {
			Published string `yaml:"published"`
			Protocol  string `yaml:"protocol"`
		}
		if node.Decode(&long) != nil || long.Protocol == "udp" {
			return node, false
		}
		host, _ := strconv.Atoi(long.Published)
		to, hit := remap[host]
		if host == 0 || !hit || to == host {
			return node, false
		}
		// Re-encode the full mapping with only published swapped, keeping
		// target/protocol/mode/host_ip and anything else it carries.
		var full map[string]any
		if node.Decode(&full) != nil {
			return node, false
		}
		full["published"] = strconv.Itoa(to)
		fresh := &yaml.Node{}
		if fresh.Encode(full) != nil {
			return node, false
		}
		return fresh, true
	}
	return node, false
}
